language: python
python: '3.7'
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install ./fastsk
script:  python ./test/run_check.py --train data/EP300.train.fasta --test data/EP300.test.fasta


